name: drawing_app_clean_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  image: ^4.5.4
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
